#!/usr/bin/env bash

GOVCORE_PORT=8001
GOVAUTH_BACKEND_PORT=8002
GOVAUTH_FRONTEND_PORT=8003
GOVBOX_PORT=8004

# Start GovCore API
cd /govcore/govcore
ruby api.rb -p $GOVCORE_PORT &

# Start GovAuth Backend
cd /govcore/govauth/backend
npm start

# Start GovAuth Frontend
cd /govauth/frontend
node server.js

# Start GovBox Frontend
cd /govauth/govbox
npm run serve